# Copyright (c) 2011 Solano Labs All Rights Reserved

development:
  api:
    scheme: http
    host: localhost
    port: 3000
    version: 1
  git:
    host: api.tddium.com
    scheme: ssh
    absolute_path: /home/git/repo
    user: git

production:
  api:
    scheme: https
    host: api.tddium.com
    version: 1
  git:
    host: api.tddium.com
    scheme: ssh
    absolute_path: /home/git/repo
    user: git

test:
  api:
    scheme: http
    host: localhost
    port: 3000
    version: 1
  git:
    host: api.tddium.com
    scheme: ssh
    absolute_path: /home/git/repo
    user: git